MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: "/home/share/chenfree/ReID/jx_vit_base_p16_224-80ecf9dd.pth" # 初始骨干权重
  NAME: 'transformer_simsiam'
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransOSS'
  STRIDE_SIZE: [16, 16]
  
  MIE: True
  MIE_COE: 3.0
  SSE: False

  # --- SimSiam Specific Settings ---
  SIMSIAM_DIM: 768  # 编码器和投影头的输出维度
  SIMSIAM_PROJ_HIDDEN_DIM: 2048 # 投影头中间层的维度
  SIMSIAM_PRED_HIDDEN_DIM: 512 # 预测头中间层的维度
  SIMSIAM_ENCODER_DEPTH: 12
  SIMSIAM_ENCODER_HEADS: 12

INPUT:
  SIZE_TRAIN: [256, 128]
  PROB: 0.5
  RE_PROB: 0.0
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASETS:
  NAMES: ('Pretrain')
  ROOT_DIR: ('/home/share/chenfree/ReID/')

DATALOADER:
  SAMPLER: 'softmax' # SimSiam不需要triplet sampler
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD' # SimSiam原文使用SGD
  MAX_EPOCHS: 200
  BASE_LR: 0.05 
  IMS_PER_BATCH: 256
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY:  0.0001
  MOMENTUM: 0.9
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50

OUTPUT_DIR: './logs/pretrain_simsiam'